<?php
//
$labels = array();
$labels['filters'] = 'Филтри';
$labels['storedfilters'] = 'Запазени филтри';
$labels['whatfilter'] = 'Филтър';
$labels['searchstring'] = 'Съдържа';
$labels['moveto'] = 'Премести в папка';
$labels['from'] = 'От';
$labels['to'] = 'Получател';
$labels['cc'] = 'Скрито копие до';
$labels['subject'] = 'Заглавие';
$labels['delete'] = 'Изтриване';
$labels['casesensitive'] = 'Различаване на малки и главни букви';
//
$messages = array();
$messages['nosearchstring'] = "Полето 'Съдържа' не може да бъде празно.";
$messages['successfullysaved'] = "Филтъра беше добавен успешно.";
$messages['unsuccessfullysaved'] = "Грешка при добавянето на филтър.";
$messages['successfullydeleted'] = "Филтъра беше премахнат успешно.";
$messages['unsuccessfullydeleted'] = "Грешка при премахването на филтър.";
$messages['msg_if_field'] = 'Ако в полето';
$messages['msg_contains'] = 'се съдържа';
$messages['msg_and_is'] = 'и е';
$messages['msg_move_msg_in'] = 'премести писмото в папка';
$messages['msg_no_stored_filters'] = "Няма добавени филтри.";
$messages['msg_moved_by_rule'] = "Бяха преместени писма, отговарящи на вашите филтри.";

?>
