<?php

$labels = array();                                
$labels['filters'] = 'Pravidla';
$labels['storedfilters'] = 'Uložená pravidla';
$labels['whatfilter'] = 'Pravidlo';
$labels['searchstring'] = 'Obsahuje';
$labels['moveto'] = 'Uložit do';
$labels['from'] = 'Od';
$labels['to'] = 'Komu';
$labels['cc'] = 'Kopie';
$labels['subject'] = 'Předmět';
$labels['delete'] = 'Smazat';

$messages = array();
$messages['nosearchstring'] = "Pole 'Obsahuje' nemůže zůstat prázdné.";
$messages['successfullysaved'] = "Pravidlo bylo uloženo.";
$messages['unsuccessfullysaved'] = "Chyba: pravidlo nebylo uloženo.";
$messages['successfullydeleted'] = "Pravidlo bylo smazánoo.";
$messages['unsuccessfullydeleted'] = "Chyba: pravidlo nebylo smazáno.";
$messages['msg_if_field'] = 'Pokud pole';
$messages['msg_contains'] = 'obsahuje';
$messages['msg_move_msg_in'] = 'uložit zprávu do';
$messages['msg_no_stored_filters'] = "Nemáte uložená pravidla.";
$messages['msg_moved_by_rule'] = "Zpráva(y), pohybuje filtrem(y)...";

?>