<?php

$labels = array();
$labels['filters'] = 'Filter';
$labels['storedfilters'] = 'Gespeicherte Filter';
$labels['whatfilter'] = 'Filter';
$labels['searchstring'] = 'Enthält';
$labels['moveto'] = 'Verschieben nach';
$labels['from'] = 'Absender';
$labels['to'] = 'Empfänger';
$labels['cc'] = 'CC';
$labels['subject'] = 'Betreff';
$labels['delete'] = 'Löschen';

$messages = array();
$messages['nosearchstring'] = "Das Feld 'Enthält' darf nicht leer sein.";
$messages['successfullysaved'] = "Filter erfolgreich gespeichert.";
$messages['unsuccessfullysaved'] = "Fehler: Filter nicht gespeichert.";
$messages['successfullydeleted'] = "Filter erfolgreich gelöscht.";
$messages['unsuccessfullydeleted'] = "Fehler: Filter nicht gelöscht.";
$messages['msg_if_field'] = 'Wenn das Feld';
$messages['msg_contains'] = 'den Inhalt';
$messages['msg_move_msg_in'] = 'aufweist, dann verschiebe die Nachricht in den Ordner';
$messages['msg_no_stored_filters'] = "Keine gespeicherten Filter.";
$messages['msg_moved_by_rule'] = "Nachricht(en) durch Filter(n) umgezogen ...";

?>