<?php

$labels = array();
$labels['filters'] = 'Filters';
$labels['storedfilters'] = 'Stored filters';
$labels['whatfilter'] = 'Filter';
$labels['searchstring'] = 'Contains';
$labels['moveto'] = 'Move to';
$labels['from'] = 'From';
$labels['to'] = 'To';
$labels['cc'] = 'CC';
$labels['subject'] = 'Subject';
$labels['delete'] = 'Delete';
$labels['MoveTop'] = 'Top';
$labels['MoveBottom'] = 'Bottom';
$labels['MoveUp'] = 'Up';
$labels['MoveDown'] = 'Down';
$labels['casesensitive'] = 'Case sensitive';

$messages = array();
$messages['nosearchstring'] = "The field 'Contains' cannot be empty.";
$messages['successfullysaved'] = "Filter successfully stored.";
$messages['unsuccessfullysaved'] = "Error: filter not stored.";
$messages['successfullydeleted'] = "Filter successfully deleted.";
$messages['unsuccessfullydeleted'] = "Error: filter not deleted.";
$messages['successfullmovedtop'] = "Filter successfully moved on top.";
$messages['unsuccessfullmovedtop'] = "Error: filter not moved on top.";
$messages['successfullmovedbottom'] = "Filter successfully moved on bottom.";
$messages['unsuccessfullmovedbottom'] = "Error: filter not moved on bottom.";
$messages['successfullmovedup'] = "Filter successfully moved up.";
$messages['unsuccessfullmovedup'] = "Error: filter not moved up.";
$messages['successfullmoveddown'] = "Filter successfully moved down.";
$messages['unsuccessfullmoveddown'] = "Error: filter not moved down.";
$messages['msg_if_field'] = 'If the field';
$messages['msg_contains'] = 'contains';
$messages['msg_and_is'] = 'and is';
$messages['msg_move_msg_in'] = 'move the message to';
$messages['msg_no_stored_filters'] = "There aren't filters stored.";
$messages['msg_moved_by_rule'] = "Message(s) moved by filter(s) to ";

?>
