<?php
/*
 +-----------------------------------------------------------------------+
 | Author: Yoni - MyRoundcube Plugins www.myroundcube.com
 +-----------------------------------------------------------------------+
 */
$labels = array();
$labels['filters'] = 'Filtros';
$labels['storedfilters'] = 'Filtros almacenados';
$labels['whatfilter'] = 'Filtro';
$labels['searchstring'] = 'Contiene';
$labels['moveto'] = 'Mover a';
$labels['from'] = 'De';
$labels['to'] = 'Para';
$labels['cc'] = 'CC';
$labels['subject'] = 'Asunto';
$labels['delete'] = 'Eliminar';

$messages = array();
$messages['nosearchstring'] = "El campo 'Contiene' no puede estar vacío.";
$messages['successfullysaved'] = "Filtro almacenado éxitosamente.";
$messages['unsuccessfullysaved'] = "Error: filtro no almacenado.";
$messages['successfullydeleted'] = "Filtro elimindo éxitosamente.";
$messages['unsuccessfullydeleted'] = "Error: filtro no eliminado.";
$messages['msg_if_field'] = 'Si el campo';
$messages['msg_contains'] = 'contiene';
$messages['msg_move_msg_in'] = 'mover mensaje a';
$messages['msg_no_stored_filters'] = "No hay filtros almacenados.";
$messages['msg_moved_by_rule'] = "Mensaje(s) movido por el filtro(s) ...";

?>
