<?php

$labels = array();
$labels['filters'] = 'Filtres';
$labels['storedfilters'] = 'Filtres actifs';
$labels['whatfilter'] = 'Filtre';
$labels['searchstring'] = 'Contient';
$labels['moveto'] = 'Déplacer vers';
$labels['from'] = 'De';
$labels['to'] = 'Pour';
$labels['cc'] = 'Copie à';
$labels['subject'] = 'Sujet';
$labels['delete'] = 'Supprimer';

$messages = array();
$messages['nosearchstring'] = "Le champ 'Contient' ne peut pas être vide.";
$messages['successfullysaved'] = "Filtre enregistré avec succés.";
$messages['unsuccessfullysaved'] = "Erreur: filtre non sauvegarder.";
$messages['successfullydeleted'] = "Filtre supprimé avec succés.";
$messages['unsuccessfullydeleted'] = "Erreur: filtre non supprimé.";
$messages['msg_if_field'] = 'Si le champ';
$messages['msg_contains'] = 'contient';
$messages['msg_move_msg_in'] = 'déplacer le message vers';
$messages['msg_no_stored_filters'] = "Il n'y a pas de filtres enregistrés.";
$messages['msg_moved_by_rule'] = "Message(s) déplacé par le filtre(s) ...";

?>