<?php

$labels = array();
$labels['filters'] = 'Filtri';
$labels['storedfilters'] = 'Filtri impostati';
$labels['whatfilter'] = 'Filtrare';
$labels['searchstring'] = 'Contiene';
$labels['moveto'] = 'Sposta in';
$labels['from'] = 'Da';
$labels['to'] = 'A';
$labels['cc'] = 'CC';
$labels['subject'] = 'Oggetto';
$labels['delete'] = 'Cancella';

$messages = array();
$messages['nosearchstring'] = "Il campo 'Contiene' non può essere vuoto.";
$messages['successfullysaved'] = "Il filtro è stato salvato con successo.";
$messages['unsuccessfullysaved'] = "Errore nel salvataggio del filtro.";
$messages['successfullydeleted'] = "Il filtro è stato eliminato con successo.";
$messages['unsuccessfullydeleted'] = "Errore nella rimozione del filtro.";
$messages['msg_if_field'] = 'Se il campo';
$messages['msg_contains'] = 'contiene';
$messages['msg_move_msg_in'] = 'sposta il messaggio in';
$messages['msg_no_stored_filters'] = 'Non è stato impostato alcun filtro';
$messages['msg_moved_by_rule'] = "Message(s) mossa da filtro(s) ...";

?>