<?php

$labels = array();
$labels['filters'] = 'Filters';
$labels['storedfilters'] = 'Opgeslagen filters';
$labels['whatfilter'] = 'Filter';
$labels['searchstring'] = 'Bevat';
$labels['moveto'] = 'Verplaaten naar';
$labels['from'] = 'Van';
$labels['to'] = 'Naar';
$labels['cc'] = 'CC';
$labels['subject'] = 'Onderwerp';
$labels['delete'] = 'Verwijderen';

$messages = array();
$messages['nosearchstring'] = "Het veld 'Bevat' mag niet leeg zijn.";
$messages['successfullysaved'] = "Filter met succes opgeslagen.";
$messages['unsuccessfullysaved'] = "Fout: filteren niet opgeslagen.";
$messages['successfullydeleted'] = "Filter met succes verwijderd.";
$messages['unsuccessfullydeleted'] = "Fout: filter niet verwijderd.";
$messages['msg_if_field'] = 'Als het veld';
$messages['msg_contains'] = 'bevat';
$messages['msg_move_msg_in'] = 'het bericht verplaatsen naar';
$messages['msg_no_stored_filters'] = "Er zijn geen opgeslagen filters.";
$messages['msg_moved_by_rule'] = "Bericht(en) verplaatst door filter(s)...";

?>