<?php

$labels = array();
$labels['filters'] = 'Reguły filtrowania';
$labels['storedfilters'] = 'Utworzone reguły filtrowania';
$labels['whatfilter'] = 'Filtruj';
$labels['searchstring'] = 'Zawiera';
$labels['moveto'] = 'Przenieś do';
$labels['from'] = 'Od';
$labels['to'] = 'Do';
$labels['cc'] = 'CC';
$labels['subject'] = 'Temat';
$labels['delete'] = 'Usuń';

$messages = array();
$messages['nosearchstring'] = "The field 'Contains' cannot be empty.";
$messages['successfullysaved'] = "Reguła filtrowania zapisana.";
$messages['unsuccessfullysaved'] = "Błąd. Nie udało się zapisać reguły filtrowania.";
$messages['successfullydeleted'] = "Reguła filtrowania została usunięta.";
$messages['unsuccessfullydeleted'] = "Błąd. Nie udało się usunąć reguły filtrowania.";
$messages['msg_if_field'] = 'Jeśli pole';
$messages['msg_contains'] = 'zawiera';
$messages['msg_move_msg_in'] = 'przenieś wiadomość do';
$messages['msg_no_stored_filters'] = "Nie ma żadnych reguł filtrowania wiadomości.";
$messages['msg_moved_by_rule'] = "Wiadomość (s) przeniesiony przez filtr (y) ...";

?>
