<?php

$labels = array();
$labels['filters'] = 'Reguły filtrowania';
$labels['storedfilters'] = 'Utworzone reguły filtrowania';
$labels['whatfilter'] = 'Filtruj';
$labels['searchstring'] = 'Zawiera';
$labels['moveto'] = 'Przenieś do';
$labels['from'] = 'Od';
$labels['to'] = 'Do';
$labels['cc'] = 'CC';
$labels['subject'] = 'Temat';
$labels['delete'] = 'Usuń';
$labels['MoveTop'] = 'Na górę';
$labels['MoveBottom'] = 'Na spód';
$labels['MoveUp'] = 'Wyżej';
$labels['MoveDown'] = 'Niżej';
$labels['casesensitive'] = 'Uwzględnij wielkość liter';

$messages = array();
$messages['nosearchstring'] = "The field 'Contains' cannot be empty.";
$messages['successfullysaved'] = "Reguła filtrowania zapisana.";
$messages['unsuccessfullysaved'] = "Błąd. Nie udało się zapisać reguły filtrowania.";
$messages['successfullydeleted'] = "Reguła filtrowania została usunięta.";
$messages['unsuccessfullydeleted'] = "Błąd. Nie udało się usunąć reguły filtrowania.";
$messages['successfullmovedtop'] = "Filtr został przenieśony na górę.";
$messages['unsuccessfullmovedtop'] = "Błąd: Nie został przeniesiony na górę.";
$messages['successfullmovedbottom'] = "Filtr został przenieśony na spód.";
$messages['unsuccessfullmovedbottom'] = "Błąd: Nie został przeniesiony na spód.";
$messages['successfullmovedup'] = "Filtr został przenieśony wyżej.";
$messages['unsuccessfullmovedup'] = "Błąd: Nie został przeniesiony wyżej.";
$messages['successfullmoveddown'] = "Filtr został przenieśony niżej.";
$messages['unsuccessfullmoveddown'] = "Błąd: Nie został przeniesiony niżej.";
$messages['msg_if_field'] = 'Jeśli pole';
$messages['msg_contains'] = 'zawiera';
$messages['msg_and_is'] = 'i jest';
$messages['msg_move_msg_in'] = 'przenieś wiadomość do';
$messages['msg_no_stored_filters'] = "Nie ma żadnych reguł filtrowania wiadomości.";
$messages['msg_moved_by_rule'] = "Wiadomość(i) przeniesiono przez filtr(y) do ";

?>
