<?php

$labels = array();
$labels['filters'] = 'Filtros';
$labels['storedfilters'] = 'Filtros guardados';
$labels['whatfilter'] = 'Filtro';
$labels['searchstring'] = 'Contém';
$labels['moveto'] = 'Mover para';
$labels['from'] = 'Remetente';
$labels['to'] = 'Destinatário';
$labels['cc'] = 'Com conhecimento';
$labels['subject'] = 'Assunto';
$labels['delete'] = 'Apagar'; 

$messages = array();
$messages['nosearchstring'] = "O campo 'Contém' não pode estar vazio.";
$messages['successfullysaved'] = "O fitro foi guardado com êxito.";
$messages['unsuccessfullysaved'] = "Erro: o filtro não foi guardado.";
$messages['successfullydeleted'] = "O filtro foi apagado com êxito.";
$messages['unsuccessfullydeleted'] = "Erro: o filtro não foi apagado.";
$messages['msg_if_field'] = 'Se o campo';
$messages['msg_contains'] = 'incluir';
$messages['msg_move_msg_in'] = 'mover a mensagem para';
$messages['msg_no_stored_filters'] = "Não existem filtros.";
$messages['msg_moved_by_rule'] = "Message (s) movido pelo filtro (s) ...";

?>