<?php

$labels = array();
$labels['filters'] = 'Filtre';
$labels['storedfilters'] = 'Filtre salvate';
$labels['whatfilter'] = 'Filtru';
$labels['searchstring'] = 'Contine';
$labels['moveto'] = 'Muta in';
$labels['from'] = 'De la';
$labels['to'] = 'Catre';
$labels['cc'] = 'CC';
$labels['subject'] = 'Subiect';
$labels['delete'] = 'Sterge';

$messages = array();
$messages['nosearchstring'] = "Campul 'Contine' nu poate fi gol.";
$messages['successfullysaved'] = "Filtru salvat cu succes.";
$messages['unsuccessfullysaved'] = "Eroare: Filtrul nu poate fi salvat.";
$messages['successfullydeleted'] = "Filtru sters cu succes.";
$messages['unsuccessfullydeleted'] = "Eroare: filtrul nu a fost sters.";
$messages['msg_if_field'] = 'Daca campul';
$messages['msg_contains'] = 'contine';
$messages['msg_move_msg_in'] = 'muta mesajul in';
$messages['msg_no_stored_filters'] = "Nici un filtru salvat.";
$messages['msg_moved_by_rule'] = "Mesaj (e) a de filtru (e) ...";

?>