<?php

$labels = array();
$labels['filters'] = 'Фильтры';
$labels['storedfilters'] = 'Правила';
$labels['whatfilter'] = 'Фильтр';
$labels['searchstring'] = 'Содержит';
$labels['moveto'] = 'Переместить';
$labels['from'] = 'От';
$labels['to'] = 'То';
$labels['cc'] = 'Копия';
$labels['subject'] = 'Тема';
$labels['delete'] = 'Удалить';

$messages = array();
$messages['nosearchstring'] = "Поле 'Содержит' не может быть пустым.";
$messages['successfullysaved'] = "Правило сохранено.";
$messages['unsuccessfullysaved'] = "Ошибка: правило не сохранено.";
$messages['successfullydeleted'] = "Правило удалено.";
$messages['unsuccessfullydeleted'] = "Ошибка: правило не удалено.";
$messages['msg_if_field'] = 'Если поле';
$messages['msg_contains'] = 'Содержит';
$messages['msg_move_msg_in'] = 'Переместить сообщение в';
$messages['msg_no_stored_filters'] = "Имеются не сохраненные правила.";
$messages['msg_moved_by_rule'] = "Письмо(а) перемещено фильтром...";

?>
