<?php

$labels = array();                                
$labels['filters'] = 'Pravidlá';
$labels['storedfilters'] = 'Uložené pravidlá';
$labels['whatfilter'] = 'Pravidlo';
$labels['searchstring'] = 'Obsahuje';
$labels['moveto'] = 'Uložiť do';
$labels['from'] = 'Od';
$labels['to'] = 'Komu';
$labels['cc'] = 'Kópia';
$labels['subject'] = 'Predmet';
$labels['delete'] = 'Zmazať';

$messages = array();
$messages['nosearchstring'] = "Pole 'Obsahuje' nemôže zostať prázdne.";
$messages['successfullysaved'] = "Pravidlo bolo uložené.";
$messages['unsuccessfullysaved'] = "Chyba: pravidlo nebolo uložené.";
$messages['successfullydeleted'] = "Pravidlo bolo zmazané.";
$messages['unsuccessfullydeleted'] = "Chyba: pravidlo nebolo zmazané.";
$messages['msg_if_field'] = 'Pokiaľ pole';
$messages['msg_contains'] = 'obsahuje';
$messages['msg_move_msg_in'] = 'uložit správu do';
$messages['msg_no_stored_filters'] = "Nemáte uložené pravidlá.";
$messages['msg_moved_by_rule'] = "Správa (y), pohybuje filtrom (y) ...";

?>