<?php

$labels = array();
$labels[\'filters\'] = \'分類器\';
$labels[\'storedfilters\'] = \'已儲存的規則\';
$labels[\'whatfilter\'] = \'搜尋欄位\';
$labels[\'searchstring\'] = \'包含\';
$labels[\'moveto\'] = \'移動至\';
$labels[\'from\'] = \'寄件人\';
$labels[\'to\'] = \'收件人\';
$labels[\'cc\'] = \'副本收件人\';
$labels[\'subject\'] = \'主旨\';
$labels[\'delete\'] = \'刪除\';

$messages = array();
$messages[\'nosearchstring\'] = \"關鍵字不可以是空的\";
$messages[\'successfullysaved\'] = \"規則儲存成功\";
$messages[\'unsuccessfullysaved\'] = \"錯誤:規則未儲存\";
$messages[\'successfullydeleted\'] = \"規則刪除成功\";
$messages[\'unsuccessfullydeleted\'] = \"錯誤:規則未刪除\";
$messages[\'msg_if_field\'] = \'如果欄位\';
$messages[\'msg_contains\'] = \'包含\';
$messages[\'msg_move_msg_in\'] = \'移動郵件\';
$messages[\'msg_no_stored_filters\'] = \"沒有已儲存的規則\";
$messages[\'msg_moved_by_rule\'] = \"消息（S）通過過濾器（S）移動...\";

?>
